apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: k6
    user: admin
    isDefault: true
    editable: true
    jsonData:
      httpMode: POST
    secureJsonData:
      password: admin123
